### PR TITLE
Add support for Dutch (`nl`)

### PR DESCRIPTION
**Pull request by matteo-tafuro**
Hey, thanks for the library! I added support for Dutch, works pretty well on my side :)

### CODE REVIEW

**Comment by alfonsrv** [comment]
Thanks for contributing @matteo-tafuro!
Can you add a couple of tests so we know how possible future changes might break the language?
Thanks! Alfons~

**Comment by alfonsrv** [comment]
Hey, any updates here? Can you supply some tests – would be awesome!

**Comment by matteo-tafuro** [comment]
@alfonsrv I just added a couple tests :)

**Comment by alfonsrv** [comment]
Looks good. Thanks for contributing and for including tests. 👍🏼

I'll add Dutch to the README.md and push a new release to PyPI

**Pull request merged**
